#!/bin/sh
if [[ -f '/data/.dbus-kostal_piko_legacy_disabled' ]] ; then
    echo "*** dbus-kostal_piko_legacy is disabled, not starting ***"
    svc -d /service/dbus-kostal_piko_legacy*
    exit 0
fi

exec 2>&1
exec python3 /data/venus.kostal_piko_legacy/kostal.py /data/venus.kostal_piko_legacy/kostal.ini

